version: '3.4'
services:
  redis:
    image: redis:latest
    container_name: 'redis'
    command: ['redis-server']
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../redis-data:/data
