version: '3.4'
services:
  redis:
    image: redis:latest
    container_name: 'redis'
    command: ['redis-server']
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../data/redis-data:/data
  mongo:
    image: mongo:latest
    container_name: 'mongo'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ../data/mongo-data:/data/db
      - ../scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
