version: '3.4'
services:
  server:
    init: true
    container_name: 'server'
    env_file:
      - ./.env
    image: 'tuedockerid1107/server:latest'
    links:
      - redis
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongo
    restart: always

  redis:
    image: 'tuedockerid1107/redis:latest'
    container_name: 'redis'
    command: ['redis-server']
    expose:
      - 6379
    volumes:
      - ../data/redis-data:/data

  mongo:
    image: 'tuedockerid1107/mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ../data/mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
